// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package me.biplobsd.rsm

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ShizukuApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class CommandRequest (
  val command: String,
  val mode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommandRequest {
      val command = pigeonVar_list[0] as String
      val mode = pigeonVar_list[1] as String?
      return CommandRequest(command, mode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      command,
      mode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CommandRequest
    return ShizukuApiPigeonUtils.deepEquals(this.command, other.command) && ShizukuApiPigeonUtils.deepEquals(this.mode, other.mode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.command)
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.mode)
    return result
  }
  override fun toString(): String {
    return "CommandRequest(command=$command, mode=$mode)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CommandResult (
  val exitCode: Long? = null,
  val output: String? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommandResult {
      val exitCode = pigeonVar_list[0] as Long?
      val output = pigeonVar_list[1] as String?
      val error = pigeonVar_list[2] as String?
      return CommandResult(exitCode, output, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      exitCode,
      output,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CommandResult
    return ShizukuApiPigeonUtils.deepEquals(this.exitCode, other.exitCode) && ShizukuApiPigeonUtils.deepEquals(this.output, other.output) && ShizukuApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.exitCode)
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.output)
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "CommandResult(exitCode=$exitCode, output=$output, error=$error)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AppInfoData (
  val packageName: String,
  val appName: String,
  val icon: ByteArray? = null,
  val isSystemApp: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppInfoData {
      val packageName = pigeonVar_list[0] as String
      val appName = pigeonVar_list[1] as String
      val icon = pigeonVar_list[2] as ByteArray?
      val isSystemApp = pigeonVar_list[3] as Boolean
      return AppInfoData(packageName, appName, icon, isSystemApp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      appName,
      icon,
      isSystemApp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AppInfoData
    return ShizukuApiPigeonUtils.deepEquals(this.packageName, other.packageName) && ShizukuApiPigeonUtils.deepEquals(this.appName, other.appName) && ShizukuApiPigeonUtils.deepEquals(this.icon, other.icon) && ShizukuApiPigeonUtils.deepEquals(this.isSystemApp, other.isSystemApp)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.appName)
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.icon)
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.isSystemApp)
    return result
  }
  override fun toString(): String {
    return "AppInfoData(packageName=$packageName, appName=$appName, icon=${icon?.contentToString()}, isSystemApp=$isSystemApp)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InstalledAppsResult (
  val apps: List<AppInfoData>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InstalledAppsResult {
      val apps = pigeonVar_list[0] as List<AppInfoData>
      return InstalledAppsResult(apps)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apps,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InstalledAppsResult
    return ShizukuApiPigeonUtils.deepEquals(this.apps, other.apps)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ShizukuApiPigeonUtils.deepHash(this.apps)
    return result
  }
  override fun toString(): String {
    return "InstalledAppsResult(apps=$apps)"
  }
}
private open class ShizukuApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommandRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommandResult.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppInfoData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstalledAppsResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CommandRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CommandResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is AppInfoData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is InstalledAppsResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val ShizukuApiPigeonMethodCodec = StandardMethodCodec(ShizukuApiPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ShizukuHostApi {
  fun runCommand(request: CommandRequest, callback: (Result<CommandResult>) -> Unit)
  fun pingBinder(): Boolean
  fun checkRootPermission(callback: (Result<Boolean>) -> Unit)
  fun requestRootPermission(callback: (Result<Boolean>) -> Unit)
  fun checkPermission(): Boolean
  fun requestPermission(callback: (Result<Boolean>) -> Unit)
  fun setStreamCommand(command: String, mode: String?)
  fun startAppInfoStream(mode: String?)
  fun getAppInfo(packageName: String, mode: String?, callback: (Result<AppInfoData?>) -> Unit)
  fun getAppVersion(): String
  fun applyThemeMode(mode: Long)

  companion object {
    /** The codec used by ShizukuHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ShizukuApiPigeonCodec()
    }
    /** Sets up an instance of `ShizukuHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ShizukuHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.runCommand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as CommandRequest
            api.runCommand(requestArg) { result: Result<CommandResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ShizukuApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ShizukuApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.pingBinder$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.pingBinder())
            } catch (exception: Throwable) {
              ShizukuApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.checkRootPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkRootPermission{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ShizukuApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ShizukuApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.requestRootPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestRootPermission{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ShizukuApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ShizukuApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.checkPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.checkPermission())
            } catch (exception: Throwable) {
              ShizukuApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestPermission{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ShizukuApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ShizukuApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.setStreamCommand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val commandArg = args[0] as String
            val modeArg = args[1] as String?
            val wrapped: List<Any?> = try {
              api.setStreamCommand(commandArg, modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              ShizukuApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.startAppInfoStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.startAppInfoStream(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              ShizukuApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.getAppInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val modeArg = args[1] as String?
            api.getAppInfo(packageNameArg, modeArg) { result: Result<AppInfoData?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ShizukuApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ShizukuApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.getAppVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAppVersion())
            } catch (exception: Throwable) {
              ShizukuApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.running_services_monitor.ShizukuHostApi.applyThemeMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.applyThemeMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              ShizukuApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class ShizukuApiPigeonStreamHandler<T>(
    val wrapper: ShizukuApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface ShizukuApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class StreamOutputStreamHandler : ShizukuApiPigeonEventChannelWrapper<String> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamOutputStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.running_services_monitor.ShizukuStreamApi.streamOutput"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = ShizukuApiPigeonStreamHandler<String>(streamHandler)
      EventChannel(messenger, channelName, ShizukuApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from ShizukuApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<String>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class AppInfoOutputStreamHandler : ShizukuApiPigeonEventChannelWrapper<AppInfoData> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: AppInfoOutputStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.running_services_monitor.ShizukuStreamApi.appInfoOutput"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = ShizukuApiPigeonStreamHandler<AppInfoData>(streamHandler)
      EventChannel(messenger, channelName, ShizukuApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from ShizukuApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<AppInfoData>) {}

override fun onCancel(p0: Any?) {}
}
      
