name: build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-android:
    runs-on: ubuntu-latest

    name: 🤖 Build Android APK

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: ☕️ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: 🛠️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.41.6'
          cache: true

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🧠 Generate code
        run: |
          flutter gen-l10n
          dart run build_runner build --delete-conflicting-outputs

      - name: 🔐 Decode Keystore
        if: github.event_name != 'pull_request'
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE }}
        run: echo "$KEYSTORE_BASE64" | base64 --decode > ${{ github.workspace }}/keystore.jks

      - name: 📝 Update key.properties
        if: github.event_name != 'pull_request'
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        run: |
          echo "storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyPassword=$KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEYSTORE_ALIAS" >> android/key.properties
          echo "storeFile=${{ github.workspace }}/keystore.jks" >> android/key.properties
        shell: bash

      - name: 🏗️ Build APK
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            flutter build apk --debug --target-platform android-arm64
          else
            flutter build apk --target-platform android-arm64 --obfuscate --split-debug-info=build/app/outputs/symbols
          fi

      - name: 📤 Upload APK Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
